{
  "formatVersion": "1.1",
  "component": {
    "group": "org.blokada.flutter.common",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 10738962,
          "sha512": "5380d4bbe1f4387ca5e309331919cc52bc315922c7a35dc3b43cd9d3da504ac50c96dda16d64e41785b34c47deeed507c2c905c73fbf157833cbd41b8965b2cc",
          "sha256": "24a858ed26385935e7ac7dc83c4309e1a8f53db0c16cb3f754ad01783531888a",
          "sha1": "502ed572d7db8ae50fd8c17cbeaca857ce8a20c9",
          "md5": "86e5325ac2c89283faf04c70f3d559ab"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 10738962,
          "sha512": "5380d4bbe1f4387ca5e309331919cc52bc315922c7a35dc3b43cd9d3da504ac50c96dda16d64e41785b34c47deeed507c2c905c73fbf157833cbd41b8965b2cc",
          "sha256": "24a858ed26385935e7ac7dc83c4309e1a8f53db0c16cb3f754ad01783531888a",
          "sha1": "502ed572d7db8ae50fd8c17cbeaca857ce8a20c9",
          "md5": "86e5325ac2c89283faf04c70f3d559ab"
        }
      ]
    }
  ]
}
