{
  "formatVersion": "1.1",
  "component": {
    "group": "org.blokada.flutter.common",
    "module": "flutter",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-debug.aar",
          "url": "flutter-1.0-debug.aar",
          "size": 16527656,
          "sha512": "ebee28632af716dbb38a2cf8a93df631dafa9dc1ef7f932a8eb612ce507ced2cba3230909956faee97a6fd6526183ae7142a1125f082a2306068078be33666ff",
          "sha256": "6ca98d482b9d173d87b95582040a0f472b7103bca6fa723d5005dfa9dd6cd1b3",
          "sha1": "6218a373218b5ae26b0a2e5b8895b2242d0b9c08",
          "md5": "da01aa8bc2c212427ff71d27cf164af5"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-debug.aar",
          "url": "flutter-1.0-debug.aar",
          "size": 16527656,
          "sha512": "ebee28632af716dbb38a2cf8a93df631dafa9dc1ef7f932a8eb612ce507ced2cba3230909956faee97a6fd6526183ae7142a1125f082a2306068078be33666ff",
          "sha256": "6ca98d482b9d173d87b95582040a0f472b7103bca6fa723d5005dfa9dd6cd1b3",
          "sha1": "6218a373218b5ae26b0a2e5b8895b2242d0b9c08",
          "md5": "da01aa8bc2c212427ff71d27cf164af5"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-release.aar",
          "url": "flutter-1.0-release.aar",
          "size": 7462239,
          "sha512": "21282fd2082863fb743dc3c39ae9ede1e3955b16c3ea13863c572802081137d24325a6e499d3f0179aef95bd6e65d44cc83491d70e6529edebc9bdc190c8cf52",
          "sha256": "28d33417156f19eca788d1b2c0f261fbc98748864d09ee52c7702e1e0aa8f53e",
          "sha1": "a78518b5940429bb46e94996791a05e589a808f5",
          "md5": "6950cdc5c94807f52f1aefe272ddc084"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-release.aar",
          "url": "flutter-1.0-release.aar",
          "size": 7462239,
          "sha512": "21282fd2082863fb743dc3c39ae9ede1e3955b16c3ea13863c572802081137d24325a6e499d3f0179aef95bd6e65d44cc83491d70e6529edebc9bdc190c8cf52",
          "sha256": "28d33417156f19eca788d1b2c0f261fbc98748864d09ee52c7702e1e0aa8f53e",
          "sha1": "a78518b5940429bb46e94996791a05e589a808f5",
          "md5": "6950cdc5c94807f52f1aefe272ddc084"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-profile.aar",
          "url": "flutter-1.0-profile.aar",
          "size": 422880,
          "sha512": "f8eb5068a530f4705dc725abf0c31f01d127bebc15a2bec8b0313a15f27d3c6f6c842be97d592aa0e71a3892612230c1b8d85b83839261c61d53e3fa4845e477",
          "sha256": "f2994b5320beeddffe7d9a6e56496a08338cff18268032cd957cb03c933dfd10",
          "sha1": "4d8d57e51dcb4eda9eaccc448169fae19b3bdf40",
          "md5": "6ba216f3b6682b68de0116402b062156"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-profile.aar",
          "url": "flutter-1.0-profile.aar",
          "size": 422880,
          "sha512": "f8eb5068a530f4705dc725abf0c31f01d127bebc15a2bec8b0313a15f27d3c6f6c842be97d592aa0e71a3892612230c1b8d85b83839261c61d53e3fa4845e477",
          "sha256": "f2994b5320beeddffe7d9a6e56496a08338cff18268032cd957cb03c933dfd10",
          "sha1": "4d8d57e51dcb4eda9eaccc448169fae19b3bdf40",
          "md5": "6ba216f3b6682b68de0116402b062156"
        }
      ]
    }
  ]
}
